_BASE_: "../Base_det.yaml"

MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  WEIGHTS: "./weights/res50_pretrain_synch-art-lsvt-rects.pth"
  TRANSFORMER:
    VOC_SIZE: 5462
  
DATASETS:
  TRAIN: ("chnsyn_train", "rects_train", "rects_val", "lsvt_train", "art_train",)
  TEST: ("rects_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (100000,)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 50000

TEST:
  EVAL_PERIOD: 100000000

OUTPUT_DIR: "output/checkpoint"
